"""empty message

Revision ID: 34d7c417d8d2
Revises: 58c3011f5764
Create Date: 2020-01-25 16:56:08.246922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d7c417d8d2'
down_revision = '58c3011f5764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'publish_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('publish_date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
