"""empty message

Revision ID: 995a42311904
Revises: 3bde9a55795f
Create Date: 2020-03-12 15:18:24.499796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995a42311904'
down_revision = '3bde9a55795f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_live', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_live')
    # ### end Alembic commands ###
