"""empty message

Revision ID: c07afd8e7051
Revises: 4b8290d75832
Create Date: 2020-01-23 13:49:08.628489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c07afd8e7051'
down_revision = '4b8290d75832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('author', 'confirm_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('confirm_password', mysql.VARCHAR(length=255), nullable=True))
    op.drop_table('blog')
    # ### end Alembic commands ###
